spring:
  security:
    oauth2:
      client:
        registration:
          twitch:
            client-id: ${ngenius.twitch.auth.client-id}
            client-secret: ${ngenius.twitch.auth.client-secret}
            client-name: twitch
            authorization-grant-type: client_credentials
            client-authentication-method: POST
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token

ngenius:
  security:
    cors:
      allowed-domains:
        - http://localhost:4200
        - https://ngeniusgaming.github.io
  twitch:
    auth:
      client-id: ${TWITCH_CLIENT_ID}
      client-secret: ${TWITCH_CLIENT_SECRET}
    team-view:
      cache-seconds: 60
      channels:
        - NGeniusGaming
        - CD_Mangaka
        - Dashr40
        - ICrazyJI
        - SetTopVox
        - ngen_duo
        - ngen_zedd
        - KasumiSSJ
        - firstofmankind
        - yiinja
        - ngenwreck
        - tappanc
        - Natejesty
        - ngen_floridaman
        - RoyalHeartv2
        - Sol_xvii
        - QueenHollow
        - iCerby
        - Minimattt
        - adanimo
    tournament:
      cache-seconds: 15
      channels:
        - AkihabaraArcade
        - milehighfightnight
        - onibakuman
        - wellbornsteak

management:
  endpoints:
    web:
      exposure:
        include: "*"
