spring:
  security:
    oauth2:
      client:
        registration:
          twitch:
            client-id: ${ngenius.twitch.auth.client-id}
            client-secret: ${ngenius.twitch.auth.client-secret}
            client-name: twitch
            authorization-grant-type: client_credentials
            client-authentication-method: POST
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token

ngenius:
  security:
    cors:
      allowed-domains:
        - http://localhost:4200
        - https://ngeniusgaming.github.io
        - https://ngeniusesports.com
  twitch:
    auth:
      client-id: ${TWITCH_CLIENT_ID}
      client-secret: ${TWITCH_CLIENT_SECRET}
  ui:
    tabs:
      team-view:
        display: true
      tournament:
        display: true
  streamer:
    channels:
      - id: NGeniusGaming
        display-name: NGeniusGaming
        platform: twitch
        tabs:
          - team-view
      - id: CD_Mangaka
        display-name: CD_Mangaka
        platform: twitch
        tabs:
          - team-view
      - id: Dashr40
        display-name: Dashr40
        platform: twitch
        tabs:
          - team-view
      - id: ICrazyJI
        display-name: ICrazyJI
        platform: twitch
        tabs:
          - team-view
      - id: SetTopVox
        display-name: SetTopVox
        platform: twitch
        tabs:
          - team-view
      - id: FirstOfMankind
        display-name: FirstOfMankind
        platform: twitch
        tabs:
          - team-view
      - id: YiinJa
        display-name: YiinJa
        platform: twitch
        tabs:
          - team-view
      - id: Natejesty
        display-name: Natejesty
        platform: twitch
        tabs:
          - team-view
      - id: NGEN_FloridaMan
        display-name: NGEN_FloridaMan
        platform: twitch
        tabs:
          - team-view
      - id: QueenHollow
        display-name: QueenHollow
        platform: twitch
        tabs:
          - team-view
      - id: iCerby
        display-name: iCerby
        platform: twitch
        tabs:
          - team-view
      - id: MiniMattt
        display-name: MiniMattt
        platform: twitch
        tabs:
          - team-view
      - id: Adanimo
        display-name: Adanimo
        platform: twitch
        tabs:
          - team-view
      - id: AkihabaraArcade
        display-name: AkihabaraArcade
        platform: twitch
        tabs:
          - tournament
      - id: milehighfightnight
        display-name: milehighfightnight
        platform: twitch
        tabs:
          - tournament
      - id: onibakuman
        display-name: onibakuman
        platform: twitch
        tabs:
          - tournament
      - id: wellbornsteak
        display-name: wellbornsteak
        platform: twitch
        tabs:
          - tournament

management:
  endpoints:
    web:
      exposure:
        include: "*"
