spring:
  security:
    oauth2:
      client:
        registration:
          twitch:
            client-id: ${ngenius.twitch.auth.client-id}
            client-secret: ${ngenius.twitch.auth.client-secret}
            client-name: twitch
            authorization-grant-type: client_credentials
            client-authentication-method: POST
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token

ngenius:
  security:
    cors:
      allowed-domains:
        - http://localhost:4200
        - https://ngeniusgaming.github.io
        - https://ngeniusesports.com
  twitch:
    auth:
      client-id: ${TWITCH_CLIENT_ID}
      client-secret: ${TWITCH_CLIENT_SECRET}
    team-view:
      channels:
        - NGeniusGaming
        - CD_Mangaka
        - Dashr40
        - ICrazyJI
        - SetTopVox
        - ngen_duo
        - ngen_zedd
        - KasumiSSJ
        - firstofmankind
        - yiinja
        - ngenwreck
        - tappanc
        - Natejesty
        - ngen_floridaman
        - RoyalHeartv2
        - Sol_xvii
        - QueenHollow
        - iCerby
        - Minimattt
        - adanimo
    tournament:
      channels:
        - AkihabaraArcade
        - milehighfightnight
        - onibakuman
        - wellbornsteak
  ui:
    tabs:
      team-view:
        display: true
      tournament:
        display: true
  streamer:
    channels:
      - id: NGeniusGaming
        platform: twitch
        tabs:
          - team-view
      - id: CD_Mangaka
        platform: twitch
        tabs:
          - team-view
      - id: Dashr40
        platform: twitch
        tabs:
          - team-view
      - id: ICrazyJI
        platform: twitch
        tabs:
          - team-view
      - id: SetTopVox
        platform: twitch
        tabs:
          - team-view
      - id: ngen_duo
        platform: twitch
        tabs:
          - team-view
      - id: ngen_zedd
        platform: twitch
        tabs:
          - team-view
      - id: KasumiSSJ
        platform: twitch
        tabs:
          - team-view
      - id: firstofmankind
        platform: twitch
        tabs:
          - team-view
      - id: yiinja
        platform: twitch
        tabs:
          - team-view
      - id: ngenwreck
        platform: twitch
        tabs:
          - team-view
      - id: tappanc
        platform: twitch
        tabs:
          - team-view
      - id: Natejesty
        platform: twitch
        tabs:
          - team-view
      - id: ngen_floridaman
        platform: twitch
        tabs:
          - team-view
      - id: RoyalHeartv2
        platform: twitch
        tabs:
          - team-view
      - id: Sol_xvii
        platform: twitch
        tabs:
          - team-view
      - id: QueenHollow
        platform: twitch
        tabs:
          - team-view
      - id: iCerby
        platform: twitch
        tabs:
          - team-view
      - id: Minimattt
        platform: twitch
        tabs:
          - team-view
      - id: adanimo
        platform: twitch
        tabs:
          - team-view
      - id: AkihabaraArcade
        platform: twitch
        tabs:
          - tournament
      - id: milehighfightnight
        platform: twitch
        tabs:
          - tournament
      - id: onibakuman
        platform: twitch
        tabs:
          - tournament
      - id: wellbornsteak
        platform: twitch
        tabs:
          - tournament

management:
  endpoints:
    web:
      exposure:
        include: "*"
