apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngen-api
  namespace: ngen-api
spec:
  selector:
    matchLabels:
      app: ngen-api
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: ngen-api
        namespace: ngen-api
    spec:
      containers:
        - name: ngen-api
          image: ngeniusgaming/ngen-api:release
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 8080
          env:
            - name: TWITCH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: twitch-credentials
                  key: twitch-client-id
            - name: TWITCH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: twitch-credentials
                  key: twitch-client-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 10
