apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ngen-api-ingress
  namespace: ngen-api
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.ngeniusgaming.us`)
      kind: Rule
      services:
        - name: ngen-api-service
          kind: Service
          port: 8080
  tls:
    certResolver: letsencrypt
    domains:
      - main: ngeniusgaming.us
        sans: [ "*.ngeniusgaming.us" ]