# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  schedule:
    # Runs every Monday at 3am MST / 10am UTC
    - cron:  '0 10 * * 1'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          DOCKER_USERNAME: ${{ secrets.DockerHubUsername }}
          DOCKER_PASSWORD: ${{ secrets.DockerHubAPiKey }}
        run: ./gradlew build test jib -Djib.to.auth.username=$DOCKER_USERNAME -Djib.to.auth.password=$DOCKER_PASSWORD
      - name: Deploy to Kubernetes # Using https://github.com/steebchen/kubectl
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KubeConfig }}
          KUBECTL_VERSION: "1.18"
        with:
          args: '"rollout restart deployment ngen-api -n ngen-api"'
