# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  continuous-deployment:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          DOCKER_USERNAME: ${{ secrets.DockerHubUsername }}
          DOCKER_PASSWORD: ${{ secrets.DockerHubAPiKey }}
        run: ./gradlew build test bootBuildImage -Pdocker.publish -Pdocker.tag=release -Pdocker.username=$DOCKER_USERNAME -Pdocker.password=$DOCKER_PASSWORD
# Not currently running this project anywhere, so disabling helm things.
#      - name: Configure kubectl and helm
#        uses: bwvolleyball/k8s-toolkit@v1.0.0
#        with:
#          config: ${{ secrets.KubeConfig }}
#          kubectl_version: v1.25.2
#          helm_version: v3.10.0
#      - name: Deploy to Kubernetes
#        run: helm upgrade ngenius-api ./kubernetes/ngenius-api --install -n ngen-api --set "sha=${{ github.sha }}"
