# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration Build

on:
  push:
    branches-ignore: [ master ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          DOCKER_USERNAME: ${{ secrets.DockerHubUsername }}
          DOCKER_PASSWORD: ${{ secrets.DockerHubAPiKey }}
        run: ./gradlew build test bootBuildImage -Pdocker.publish -Pdocker.tag=snapshot -Pdocker.username=$DOCKER_USERNAME -Pdocker.password=$DOCKER_PASSWORD
      - name: Deploy to Kubernetes # Using https://github.com/steebchen/kubectl
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KubeConfig }}
          version: v1.21.5
          command: get pods -n ngen-api
      - name: Test Kubernetes
        run: kubectl version
