# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration Build

on:
  push:
    branches-ignore: [ master ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and Test
        run: ./gradlew build test
      # build the x86 image
      - name: x86 Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DockerHubUsername }}
          DOCKER_PASSWORD: ${{ secrets.DockerHubAPiKey }}
        run: ./gradlew bootBuildImage -Pdocker.publish -Pdocker.tag=snapshot -Pdocker.username=$DOCKER_USERNAME -Pdocker.password=$DOCKER_PASSWORD
      # build the arm image
      - name: arm Docker Image
        uses: pguyot/arm-runner-action@v2
        env:
          DOCKER_USERNAME: ${{ secrets.DockerHubUsername }}
          DOCKER_PASSWORD: ${{ secrets.DockerHubAPiKey }}
        with:
          import_github_env: 'yes'
          base_image: raspios_lite_arm64:latest
          commands: ./gradlew bootBuildImage -Pdocker.publish -Pdocker.tag=snapshot -Pdocker.username=$DOCKER_USERNAME -Pdocker.password=$DOCKER_PASSWORD
