# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Kubectl Tester

on:
  push:
    branches-ignore: [ master ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure Kubectl
        uses: bwvolleyball/kubectl@master
        with:
          config: ${{ secrets.KubeConfig }}
          kubectl_version: v1.21.5
          helm_version: v3.7.0
      - name: Use Kubectl to Check Remote Version
        run: kubectl version && kubectl get pods -n ngen-api
      - name: Check Helm Version
        run: helm version
