# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Verify Helm Chart

on:
  push:
    branches-ignore: [ master ]

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
# Not currently running this project anywhere, so disabling helm things.
#      - name: Configure Kubectl
#        uses: bwvolleyball/k8s-toolkit@v1.0.0
#        with:
#          config: ${{ secrets.KubeConfig }}
#          kubectl_version: v1.25.2
#          helm_version: v3.10.0
#      - name: Verify Helm Chart
#        run: helm template ngenius-api ./kubernetes/ngenius-api -n ngen-api --set "sha=${{ github.sha }}" | kubectl apply --dry-run=client -f -
